### ISSUE TITLE
Clean up last checkpoint on checkpoint writing failures

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#53] opened 2022-05-06 12:27 UTC
Run failed when writing checkpoints in one of our compute envs, and the checkpoints were left in a corrupted state.

Partial output of ls -la in the directory:
```
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:56 checkpoint_23_22750-model_part-7-shard96.pt.tmp
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:56 checkpoint_23_22750-model_part-7-shard97.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:56 checkpoint_23_22750-model_part-7-shard98.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:53 checkpoint_23_22750-model_part-7-shard99.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:56 checkpoint_23_22750-model_part-7-shard9.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard0.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:54 checkpoint_last-model_part-0-shard100.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:54 checkpoint_last-model_part-0-shard101.pt
-rw-rw-r--  1 susanz susanz  583649007 Mar  5 21:54 checkpoint_last-model_part-0-shard102.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard103.pt
-rw-rw-r--  1 susanz susanz  581828608 Mar  5 21:56 checkpoint_last-model_part-0-shard104.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard112.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard119.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard121.pt
-rw-rw-r--  1 susanz susanz          0 Mar  5 21:56 checkpoint_last-model_part-0-shard122.pt
```

On automatic requeue, we try to load from latest checkpoint, which failed due to the corruption.

We should add a step to cleanup corrupted checkpoints and restart from the last non-corrupted checkpoint.

**Comment by punitkoura** [comment] 2022-06-13 22:17
Steps to reproduce - 
1. Start a training run and wait for three checkpoints to be written.
2. Remove some files from the last checkpoint, and try to resume training using the --resume-failed flag.
3. The training step would fail, since we would not be able to load the last checkpoint.
4. Fix the checkpoint loading code to fallback to the last good checkpoint.

**Comment by punitkoura** [comment] 2022-07-18 23:30
Fixed by https://github.com/facebookresearch/metaseq/pull/158 , feel free to reopen if needed. Thanks!

**Closed by punitkoura** 2022-07-18 23:30 UTC
Labels: enhancement, help wanted
