### ISSUE TITLE
OPT-IML Bench release?

### ISSUE THREAD

**Issue by yhg0112** [facebookresearch/metaseq#630] opened 2023-02-03 02:25 UTC
Is OPT-IML Bench on release or are there any plan to release OPT-IML Bench?

If OPT-IML Bench is currently publicly available, where can I download the train/valid/test splits?

**Comment by evi-Genius** [comment] 2023-02-17 06:40
I have the same question.

**Comment by suchenzang** [comment] 2023-03-27 18:10
Duplicate of https://github.com/facebookresearch/metaseq/issues/619

**Closed by suchenzang** 2023-03-27 18:10 UTC
Labels: question
