### ISSUE TITLE
Meeting RuntimeError: torch.distributed is not yet initialized but process group is requested.

### ISSUE THREAD

**Issue by zhisbug** [facebookresearch/metaseq#80] opened 2022-05-10 02:08 UTC
#### What is your question?
I downloaded the 50M model weight and put it under my local path `/local/opt/350M`. I copied all the assets needed under the path as well, including the vocab file and others.

I installed all the required dependencies following the setup doc.

I then tried to launch a service following the [instruction here](https://github.com/facebookresearch/metaseq/blob/main/docs/api.md#launching-the-api) using the command `metaseq-api-local`

But met the following error:
```python
2022-05-10 02:06:39 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-10 02:06:39 | INFO | metaseq.tasks.language_modeling | dictionary: 50272 types
2022-05-10 02:06:39 | INFO | metaseq.hub_utils | loading model(s) from /home/ubuntu/opt/reshard.pt
['/home/ubuntu/opt/reshard.pt']
2022-05-10 02:06:40 | INFO | metaseq.checkpoint_utils | Done reading from disk
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/parax-efs/pycharm/opt/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/parax-efs/pycharm/opt/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/parax-efs/pycharm/opt/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_mix_prec_layer_norm_cuda...
Traceback (most recent call last):
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq-env/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq', 'console_scripts', 'metaseq-api-local')())
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq_cli/interactive_hosted.py", line 300, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/distributed/utils.py", line 263, in call_main
    return main(cfg, **kwargs)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/hub_utils.py", line 485, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/checkpoint_utils.py", line 504, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/hub_utils.py", line 476, in _build_model
    return fsdp_wrap(model)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 145, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/fairscale/fairscale/nn/wrap/auto_wrap.py", line 170, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 281, in __init__
    self.process_group = process_group or get_process_group_cached()
  File "/home/ubuntu/parax-efs/pycharm/opt/metaseq/fairscale/fairscale/utils/parallel.py", line 92, in get_process_group_cached
    raise RuntimeError("torch.distributed is not yet initialized but process group is requested.")
RuntimeError: torch.distributed is not yet initialized but process group is requested.
```

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): Ubuntu
 - How you installed metaseq (`pip`, source): `pip install -e .`
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by zhisbug** [comment] 2022-05-10 02:23
similar error with #23

**Comment by suchenzang** [comment] 2022-05-12 05:36
Closing as duplicate of https://github.com/facebookresearch/metaseq/issues/23

**Closed by suchenzang** 2022-05-12 05:36 UTC
Labels: question
