### ISSUE TITLE
How to use 1.3B OPT weights in `metaseq-api-local` API?

### ISSUE THREAD

**Issue by ParadoxZW** [facebookresearch/metaseq#61] opened 2022-05-08 08:49 UTC
I'm trying to use 1.3B OPT weights in `metaseq-api-local` API and test some inference examples. But I got stucked.

There are two reshard files of 1.3B OPT. But `CHECKPOINT_LOCAL` in `constants.py` can only point to a `reshard.pt` file. What is the correct way to load these two reshard files? (P.S. the comments in `constants.py`  says `MODEL_SHARED_FOLDER = "/example/175B/reshard_no_os"` but there is `CHECKPOINT_FOLDER = os.path.join(MODEL_SHARED_FOLDER, "175B", "reshard_no_os")` in line 49, is this also a mistake?

**Comment by soloice** [comment] 2022-05-08 09:32
You can modify the paths manually to load different models. Also, I think [this script](https://github.com/facebookresearch/metaseq/pull/60) is related.

**Comment by ParadoxZW** [comment] 2022-05-08 13:43
@soloice I know that we can modify path to load different models. My question is `CHECKPOINT_LOCAL` can only point to a ckpt file but not a list of reshard file.

**Comment by soloice** [comment] 2022-05-08 14:54
I have the same question. I assume this is not a bug: the only thing missing here is a script to merge all sharded checkpoints.

**Comment by ParadoxZW** [comment] 2022-05-09 13:14
I guess there is a way to direct load two reshard file (and infer under the strategy of model paralleling) rather than merging them.

**Comment by suchenzang** [comment] 2022-05-12 05:43
Consolidating all asks for model loading into https://github.com/facebookresearch/metaseq/issues/88, which will be released soon from HuggingFace.

We also have https://github.com/facebookresearch/metaseq/issues/78 and https://github.com/facebookresearch/metaseq/issues/77 open to fix some of these usability issues on our end.

**Closed by suchenzang** 2022-05-12 05:43 UTC
Labels: bug
