### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'gradient_predivide_factor'

### ISSUE THREAD

**Issue by deekshapandit-machani** [facebookresearch/metaseq#112] opened 2022-05-20 11:23 UTC
## ❓ Questions and Help
I am trying to run the metaseq set up steps in colab notebook using https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md. Then I run the ```metaseq-api-local``` command and get a TypeError: __init__() got an unexpected keyword argument 'gradient_predivide_factor'

#### What is your question?
Please let me know if I am doing anything wrong.
#### Stack Trace

 ````
2022-05-20 11:08:09 | INFO | metaseq_cli.interactive | Local checkpoint copy already exists, skipping copy
2022-05-20 11:08:11 | INFO | metaseq.hub_utils | loading model(s) from /content/drive/MyDrive/OPT_model/reshard.pt
2022-05-20 11:08:14 | INFO | metaseq.checkpoint_utils | Done reading from disk
Detected CUDA files, patching ldflags
Emitting ninja build file /Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_mix_prec_layer_norm_cuda...
Traceback (most recent call last):
  File "/usr/local/bin/metaseq-api-local", line 33, in <module>
    sys.exit(load_entry_point('metaseq==0.0.1', 'console_scripts', 'metaseq-api-local')())
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq_cli/interactive_hosted.py", line 294, in cli_main
    dist_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/distributed/utils.py", line 263, in call_main
    return main(cfg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq_cli/interactive_hosted.py", line 156, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/hub_utils.py", line 492, in load_model
    build_model_hook=_build_model,
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/checkpoint_utils.py", line 503, in load_model_ensemble_and_task
    model = build_model_hook(cfg, task)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/hub_utils.py", line 476, in _build_model
    return fsdp_wrap(model)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/distributed/fully_sharded_data_parallel.py", line 145, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/fairscale/nn/wrap/auto_wrap.py", line 187, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/distributed/fully_sharded_data_parallel.py", line 48, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'gradient_predivide_factor'

**Comment by suchenzang** [comment] 2022-05-23 10:49
Are you on the `prefetch_fsdp_params_simple` branch of fairscale?

**Comment by deekshapandit-machani** [comment] 2022-05-23 10:53
Yes the fairscale branch is ```prefetch_fsdp_params_simple```

**Comment by deekshapandit-machani** [comment] 2022-05-23 11:26
Yes I see the same line in fairscale. I just tried to comment it out and I do not see the error anymore. But I do not think that is the right way to go about it.
Yes I do ```pip install -e .``` when I check out the fairscale branch.

**Comment by suchenzang** [comment] 2022-06-04 23:16
Unable to reproduce this error on my end - closing for now. Please re-open if you continue to see this error (and include information on all the branches / commits you are on).

**Closed by suchenzang** 2022-06-04 23:16 UTC
Labels: question
